### ISSUE TITLE
如何加载动态国际化json？

### ISSUE THREAD

**Issue by zhanglingsi1** [onpaik/umi-lib-paik#1]
关于动态加载国际化数据，如果国际化资源是从远程获取的json，而不是在messages目录下配好的文件，这种情况支持吗？求指教@onpaik

**Comment by zhanglingsi1** [comment]
@onpaik  多谢，这个版本试了下可行。
另外还有个问题咨询下：
组件被<code>withIntl</code>包装后，<code>intl</code>这个对象被注入到该组件的<code>props</code>内，<code>formatMessage</code>也变成变成从props => intl内获取了；
如何在<code>models</code>里使用动态国际化呢？比如：用户操作结果提示，formatMessage({ id: "***" })

**Comment by onpaik** [comment]
@zhanglingsi1 
1.  对，`withIntl` 通过 `react-intl`提供的api，注入了`intl`对象，也可从`umi/locale`获取
2.  `modles` 加载国际化，我先去试试怎么弄，~~

**Comment by zhanglingsi1** [comment]
从<code>umi/locale</code>获取的<code>formatMessage</code>拿不到组件内的动态国际化资源(私有资源)

**Comment by onpaik** [comment]
> 从`umi/locale`获取的`formatMessage`拿不到组件内的动态国际化资源(私有资源)

这样呀，这种情况还没测试过

**Comment by onpaik** [comment]
有点尴尬，`umi/locale`里的api只能拿到本地的国际化数据，props里面的才能拿到`public/lang`或者 远程的国际化数据，暂时没有直接办法解决，可通过如下方式实现

1.  model内使用动态国际化，可将转换后的国际化信息传递进model
2.  定义通用型提示、文字到本地，不通过动态获取。比如你上面提到的`用户操作结果提示，formatMessage({ id: "***" })`

**Comment by zhanglingsi1** [comment]
> 有点尴尬，`umi/locale`里的api只能拿到本地的国际化数据，props里面的才能拿到`public/lang`或者 远程的国际化数据，暂时没有直接办法解决，可通过如下方式实现
> 
> 1. model内使用动态国际化，可将转换后的国际化信息传递进model
> 2. 定义通用型提示、文字到本地，不通过动态获取。比如你上面提到的`用户操作结果提示，formatMessage({ id: "***" })`

您好，因为目前工程是将国际化全量加载改造成动态加载，<code>formatMessage</code>都是从<code>umi/locale</code>获取的，若改成从<code>props/intl</code>获取，不同的地方用<code>formatMessage</code>之前还得先声明，改动有点大，我暂时是这么改的：
![_20190214100322](https://user-images.githubusercontent.com/14800750/52758190-5abfba00-3042-11e9-8798-58c6a4d1b043.png)

1.`withIntl` 注入`intl`对象后，将该对象覆盖本地的全局`intl`，这样能保证从`umi/locale`获取的`formatMessage`能拿到动态资源，`model`也能使用这部分动态资源了。
2.暂时测试是没啥问题，不知道有没有资源污染等隐患

**Comment by onpaik** [comment]
@zhanglingsi1  根据你的方法，已更新。3.1.6 版本
