### ISSUE TITLE
修改动态国际化不热更新

### ISSUE THREAD

**Issue by zhanglingsi1** [onpaik/umi-lib-paik#3]
每次修改资源后，需要手动执行`umi intl`，影响了开发体验。@onpaik请问下这个修复版本大概是什么时候

**Comment by onpaik** [comment]
@zhanglingsi1  我看看要怎么改哈，因为umi内部有文件更新检测，如果在umi机制下，会造成死循环，

**Comment by onpaik** [comment]
@zhanglingsi1 3.1.8已经支持

**Comment by zhanglingsi1** [comment]
> @zhanglingsi1 3.1.8已经支持

感谢，我去试试
